---
platform: linux
inputs:
- name: git-repo
run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      docker run -it --rm mbhave/spring-boot-dcind-image echo "Hello World"
