---
platform: linux
inputs:
- name: git-repo
run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      docker run -it --rm springci/spring-boot-ci-image:master git-repo/ci/scripts/test.sh
